# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d97cb2484199764f9b50cff931ba5b87"
application_url = "https://part-rider-infected-lib.trycloudflare.com"
embedded = true
name = "first-app"
handle = "first-app-1168"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://part-rider-infected-lib.trycloudflare.com/auth/callback",
  "https://part-rider-infected-lib.trycloudflare.com/auth/shopify/callback",
  "https://part-rider-infected-lib.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "mujeeb-e-store.myshopify.com"
automatically_update_urls_on_dev = true
